# Generated by Django 3.1.6 on 2021-03-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(default='Null', max_length=250)),
                ('studentClass', models.CharField(default='Null', max_length=250)),
            ],
        ),
    ]
